Building installation list of modules + test module folders

diff --git a/pand b/pand
--- a/pand
+++ b/pand
@@ -1,11 +1,15 @@
 #!/bin/bash
 
+if [ `id -u` -ne 0 ]; then
+	echo "Error: You must be root to run this script!"
+	exit 1
+fi
+
 ADMIN_FOLDER="./admin"
-MODULE_FOLDER="./modules"
 
 if [ $# -eq 0 ] ; then
 #   Первоначальная настройка сервера
     . "$ADMIN_FOLDER/init.sh"
 else
 #   Администрирование
-	. "$MODULE_FOLDER/admin.sh"
+	. "$ADMIN_FOLDER/admin.sh"
